services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
